version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: PaceTrack-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Asdzxc123!
      MYSQL_DATABASE: pacetrack-data
      MYSQL_USER: przedtop
      MYSQL_PASSWORD: Asdzxc123!
    ports:
      - "3306:3306"
    volumes:
      - data:/data/lib/mysql
    networks:
      - network1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pacetrack-phpmyadmin
    restart: always
    ports:
      - "3307:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Asdzxc123!
    depends_on:
      - db
    networks:
      - network1

networks:
  network1:

volumes:
  data: